---

- name: Run Kibana in a Docker container
  docker_service:
    project_name: "kibana_docker"
    definition:
      version: "2"
      services:
        kibana:
          image: "docker.elastic.co/kibana/kibana:6.1.3"
          ports:
            - "5601:5601"
          environment:
              SERVER_NAME: kibana
              ELASTICSEARCH_URL: http://192.168.181.132:9200
