---

- name: Deploy ec2 instance
  ec2:
    region: "{{ ec2_region }}"
    key_name: elk
    group: Private Network SG
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    wait: true
    exact_count: "{{ ec2_count }}"
    vpc_subnet_id: "{{ subnet_id }}"
    assign_public_ip: false
    instance_tags:
      Name: AnsiblePrivateInstance
      Role: PrivateInstanceFromAnsible
      Creator: Carlos Francia
      Tool: Ansible
    count_tag:
      Name: private-instance
  register: ec2

- name: debug Hostvars
  debug:
    var: hostvars

- name: debug ec2
  debug:
    var: ec2.tagged_instances

- name: Add instances to private servers group
  add_host:
    hostname: "{{ item.private_ip }}"
    groupname: private-servers
  with_items: "{{ ec2.tagged_instances }}"

- name: debug Hostvars2
  debug:
    var: hostvars

- name: Wait dor ec2 instance to come online
  delegate_to: 35.178.71.17
  wait_for:
    port: 22
    host: "{{ item.private_ip }}"
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.tagged_instances }}"

